tidb-toolkit: Fix tikv-ctl local mode
Update the tikv-ctl local mode:

- Use `./tikv-ctl` as `tikv-ctl` is not in the `$PATH`
- Use `--data-dir` instead of `--db` (see also
  https://github.com/tikv/website/issues/306 )

```
/ # tikv-ctl --db /var/lib/tikv/db size -r 2
sh: tikv-ctl: not found
/ # ./tikv-ctl --db /var/lib/tikv/db size -r 2
error: Invalid value for '--db <db>': DEPRECATED!!! Use --data-dir and --config instead
/ # ./tikv-ctl --data-dir /var/lib/tikv size -r 2
[2021/11/05 15:40:04.196 +00:00] [INFO] [mod.rs:118] ["encryption: none of key dictionary and file dictionary are found."]
[2021/11/05 15:40:04.196 +00:00] [INFO] [mod.rs:479] ["encryption is disabled."]
[2021/11/05 15:40:04.196 +00:00] [WARN] [config.rs:587] ["compaction guard is disabled due to region info provider not available"]
[2021/11/05 15:40:04.196 +00:00] [WARN] [config.rs:682] ["compaction guard is disabled due to region info provider not available"]
region id: 2
cf default region size: 0B
cf write region size: 0B
cf lock region size: 0B
/ # ./tikv-ctl --version
TiKV Control (tikv-ctl)
Release Version:   5.2.1
Edition:           Community
Git Commit Hash:   2c99f317d4ba125b772a8b94a6c3c0eb9d07ac59
Git Commit Branch: heads/refs/tags/v5.2.1
UTC Build Time:    2021-09-08 02:32:36
Rust Version:      rustc 1.56.0-nightly (2faabf579 2021-07-27)
Enable Features:   jemalloc mem-profiling portable sse protobuf-codec test-engines-rocksdb cloud-aws cloud-gcp
Profile:           dist_release
```